### ISSUE TITLE
Support for Django 3.2

### ISSUE THREAD

**Issue by mpoli** [Adrian-Turjak/wagtail-robots#12]
Django 3.2 has relevant changes that are incompatible with the current release of wagtail-robots. The change in AutoField from django 3.1 to 3.2 LTS creates the behavior of migration that generates an ever-missing migration, and makemigrations want to create this AutoField change, and it will not go away without a release that addresses the new AutoField in django 3.2.

wagtail-robots seems to have drifted away from django-robots enough that attempts to migrate to django-robots will generate a catastrophic database migration path, given that they seem to use the same table names.

Django-robots commit https://github.com/jazzband/django-robots/commit/70da7606974b915d57e038f8bdf31c0b21be7e45 addresses and fixes this issue for them.

**Comment by unexceptable** [comment]
Will hopefully get a chance to take a look at that soon! Thanks for the link to how they handled it. :)
