### ISSUE TITLE
Support for Django 4.0

### ISSUE THREAD

**Issue by DouglasMcKey** [Adrian-Turjak/wagtail-robots#13]
I encountered some issues when upgrading my software to 
Django 4.0
Wagtail 2.16

The issues were within wagtail-robots (at the time of writing).

I modified the following to resolve the issue (in development environment):

1) models.py

line 5:
from django.utils.translation import ugettext_lazy as _

change to
from django.utils.translation import gettext_lazy as _

---------------------------------------------------------
2) urls.py

line 1:
from django.conf.urls import url

change to:
from django.urls import re_path

line 6:
url(r'^$', rules_list, name='robots_rule_list'),

changed to:
re_path(r'^$', rules_list, name='robots_rule_list'),
---------------------------------------------------------

**Comment by unexceptable** [comment]
The fixes for this should now be merged into master, and will be released soon. Please retest with the latest release when I push it. If you still encounter issues, I will reopen this issue and dig into them!
