### ISSUE TITLE
Rule admin crashes if a site set not having a name

### ISSUE THREAD

**Issue by kelvan** [Adrian-Turjak/wagtail-robots#9]
wagtail sites do not need to have a site_name, but wagtail-robot breaks if there is a rule with a site assigned that does not have a name:
https://github.com/Adrian-Turjak/wagtail-robots/blob/26f12c919cc1f617122f340b426c18cf5f944b6f/robots/wagtail_hooks.py#L19

`sequence item 0: expected str instance, NoneType found`

Steps to reproduce:

1. Create a wagtail `Site` without a name
2. Create a rule assigning this site
3. Save

**Comment by unexceptable** [comment]
ty for the report and the fix!

**Comment by unexceptable** [comment]
I've now also actually pushed the fixed version to pypi! Sorry about the delay. 0.3.1 includes the fix.
